<?php

namespace DigitalPilot\CmsBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends DocumentRepository
{


}