<?php

namespace DigitalPilot\CmsBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * FormCustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormCustomerRepository extends DocumentRepository
{
    public function updateOneById($_id, $isActif)
    {
        return $this->createQueryBuilder('Customer')
            ->findAndUpdate()
            ->returnNew()
            ->field('_id')->equals($_id)

            // Update found Trader
            ->field('isActif')->set($isActif)
            ->getQuery()
            ->execute();
    }
}